recipes-neo-ai/neo-ai-tvm/neo-ai-tvm.bb, recipes-neo-ai/neo-ai-tvm/neo-ai-tvm/0001-CMakeLists-install-unit-tests.patch
* add run-time depends of Python3 decorator
* use newer code (Mon Oct 7) from TVM master branch
* update patch file accordingly
Signed-off-by: Jianzhong Xu <xuj@ti.com>
N/A
Fix TVM runtime problem:
* add run-time depends of Python3 decorator
* use newer code (Mon Oct 7) from TVM master branch
* update patch file accordingly
=> neo-ai-tvm: fix TVM runtime problem

recipes-greengrass/greengrass-core-sdk/aws-greengrass-core-sdk-python_git.bb, recipes-greengrass/greengrass-core/greengrass_1.10.0.bb
- Having python3 as a DEPENDS did not install all the necessary modules for runtime, thus a RDEPENDS python3 was required 
- Updated hashes for aarch64/arm to greengrass release 1.10.0
=> Fixed missing RDEPENDS for python sdk and updated aarch64/arm hashes

recipes-greengrass/greengrass-core/greengrass.inc
The /etc/sysctl.conf file may contain commented 'protected_.*links' lines.
If these lines exist, postinst() will no longer enable protection for
hardlinks and softlinks. This patch fixes this by ignoring these
commented lines.
Signed-off-by: Codrin Ciubotariu <codrin.ciubotariu@microchip.com>
=> greengrass-core: Ignore commented sysctl variables

recipes-greengrass/greengrass-core/greengrass.inc
The post install script updates the fstab with an entry to mount cgroup
at boot time. However, since the mount service has a lower runlevel than
greengrass (3 vs 80), the cgroup fs is not mounted at first boot. Fix
this by manually running 'mount -a' in the post install script.
Signed-off-by: Codrin Ciubotariu <codrin.ciubotariu@microchip.com>
=> greengrass: Fix cgroup mount at first boot

recipes-greengrass/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Add the aws-iot-securetunneling-localproxy recipe.
Here is the documentation from AWS [https://docs.aws.amazon.com/iot/latest/developerguide/secure-tunneling.html](https://docs.aws.amazon.com/iot/latest/developerguide/secure-tunneling.html) about it.
Notes. I disabled the statically linkage of Protobuf lite because by default Protobuf produces shared library. In its CMakefiles, protobuf can either generate shared or static. To use the default static libraries required by localproxy, the user would have to give up the shared library, which could fail many other recipes. I don't think it's good to force a change of a build just for this recipe is good, hence the sed commands.
I tested it, works well on qemu since the tunnel works from my laptop to the VM.
Any …
=> Add aws-iot-securetunneling-localproxy recipe

conf/layer.conf, recipes-greengrass/greengrass-core/greengrass.inc, recipes-greengrass/greengrass-core/greengrass_1.10.1.bb
*Issue #61 *
The location for the bbappend files needs to be configured in the layer config, otherwise it is not picked up by bitbake. Depending on the DISTRO variable, it will use either the arago directory or the base directory.
=> Move distro dependent kernel config to layer config

recipes-greengrass/greengrass-core-sdk/aws-greengrass-core-sdk-c_git.bb
To resolve following error,
ERROR: aws-greengrass-core-sdk-c-git-r0 do_populate_lic: QA Issue: aws-greengrass-core-sdk-c: Recipe file fetches files and does not have license file information (LIC_FILES_CHKSUM) [license-checksum]
ERROR: aws-greengrass-core-sdk-c-git-r0 do_populate_lic: Fatal QA errors found, failing task.
ERROR: aws-greengrass-core-sdk-c-git-r0 do_populate_lic: Function failed: populate_lic_qa_checksum
ERROR: Logfile of failure stored in: /home/sysadmin/git/QDN/workSpace/apq8009/apps_proc/build-qti-distro-fullstack-debug/tmp-glibc/work/armv7ahf-neon-oe-linux-gnueabi/aws-greengrass-core-sdk-c/git-r0/temp/log.do_populate_lic.19416
ERROR: Task (/home/sysadmin/git/QDN/workSpace/apq8009/apps_proc/poky/meta-aws/recipes-greengrass/greengrass-core-sdk/aws-greengrass-core-sdk-c_git. …
=> missing licence file path and checksum were added

recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2.inc
Description of changes:
Since the aws-iot-device-sdk-python-v2 recipe uses AUTOREV, the changes to LICENSE in https://github.com/aws/aws-iot-device-sdk-python-v2 result in a new md5sum breaking the verification. This PR updates the checksum in the recipe to match the new version of LICENSE.
=> aws-iot-device-sdk-python-v2: fix LIC_FILES_CHKSUM

recipes-greengrass/greengrass-core-sdk/aws-greengrass-core-sdk-c_git.bb
* see oe-core base.bbclass changes from:
https://lists.openembedded.org/g/openembedded-core/message/143159
https://lists.openembedded.org/g/openembedded-core/message/143161
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
=> aws-greengrass-core-sdk-c: don't use trailing slash in S

recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2.inc
aws-iot-device-sdk-python-v2 has renamed the master branch to main
It would also be good if this could be backported into relevant release branches.
=> aws-iot-device-sdk-python-v2: master branch is renamed to main

recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2.inc
Signed-off-by: Arnstein Kleven <arnsteinkleven@gmail.com>
Seems like the aws-iot-device-sdk-python-v2 repo changed the name of their master branch to main, breaking the build.
Changing BRANCH from master to main. 
=> Change to new master branch name

recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2.inc
The branch of aws-iot-device-sdk-python-v2 has been changed master to main
Issue #, if available:
I got errors as below.
File "bitbake/lib/bb/fetch2/git.py", line 230, in Git.urldata_init(ud=<bb.fetch2.FetchData object at 0x7fee5bf77160>, d=<bb.data_smart.DataSmart object at 0x7fee5c8a4a58>):
>        ud.setup_revisions(d)
File "bitbake/lib/bb/fetch2/init.py", line 1314, in FetchData.setup_revisions(d=<bb.data_smart.DataSmart object at 0x7fee5c8a4a58>):
for name in self.names:
> self.revisions[name] = srcrev_internal_helper(self, d, name)
File "bitbake/lib/bb/fetch2/init.py", line 1177, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7fee5bf77160>, d=<bb.data_smart.DataSmart object at 0x7fee5c8a4a58>, name='aws-iot-device-sdk-python-v2'):
if srcrev == "AUTOINC":
> srcrev = …
=> meta-aws: aws-iot-device-sdk-python-v2: branch transition master to main

recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.6.0.bb
The master branch was renamed to main for aws-iot-device-sdk-cpp-v2
ERROR: aws-iot-device-sdk-cpp-v2-1.6.0-r0 do_fetch: Fetcher failure: Unable to find revision 65b8344ddb6173d312dff4e759a0dfbc05a97e4c in branch master even from upstream
ERROR: aws-iot-device-sdk-cpp-v2-1.6.0-r0 do_fetch: Fetcher failure for URL: 'git://github.com/aws/aws-iot-device-sdk-cpp-v2.git;branch=master;name=aws-iot-device-sdk-cpp-v2
=> meta-aws: aws-iot-device-sdk-cpp-v2: fix BRANCH name

recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2.inc
* master branch was renamed to main and even just parsing
this recipe fails with:
bb.data_smart.ExpansionError: Failure expanding variable SRCPV,
expression was ${@bb.fetch2.get_srcrev(d)} which triggered
exception FetchError: Fetcher failure: Unable to resolve
'master' in upstream git repository in git ls-remote output
for github.com/aws/aws-iot-device-sdk-python-v2.git
because of AUTOREV use instead of fixed SRCREV
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
=> aws-iot-device-sdk-python-v2.inc: fix BRANCH name and use fixed SRCREV

recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2.inc
The master branch was renamed to main for aws-iot-device-sdk-python-v2.
=> meta-aws: aws-iot-device-sdk-python-v2: fix BRANCH name

recipes-devtools/amazon-corretto/corretto-11-bin_11.0.9.12.1.bb, recipes-devtools/amazon-corretto/corretto-8-bin_8.275.01.1.bb
Amazon Corretto version 8 recipe file is included. It was tested on an `armv8` board. The build is successful with this version of the recipe file. The latest version of Corretto that supports "aarch64" and "x64" platforms is 8.275.01.1. This recipe file is based on this version.
=> Amazon Corretto Version 8 recipe

recipes-devtools/amazon-corretto/corretto-11-bin_11.0.9.12.1.bb
*Issue # N/A:*
Hey guys,
Found a small typo when trying to build `greengrass-bin` for rpi4!
The SRC_URI for this arch was wrong.
=> Fix Amazon Corretto 11 SRC_URI for armv7

conf/layer.conf, recipes-devtools/python/python3-botocore_1.20.36.bb, recipes-devtools/python/python3-s3transfer_0.3.6.bb, recipes-support/awscli/awscli_1.19.36.bb
This adds a recipes for awscli and its dependencies. It's sometimes useful to have aws on a custom linux distro for development and debugging purposes. The first patch in the series makes the layer depend on meta-python.
=> Add a recipe for awscli

recipes-support/python3-jmespath/python3-jmespath_0.10.0.bb
- SRC_URI modified to point to tag 0.10.0
- LIC_FILES_CHKSUM modified to fetch file LICENSE.txt (file LICENSE doesn't
exist)
*Issue #, if available:* No issue available
*Description of changes:* On branch gatesgarth, recipe `python3-jmespath` doesn't build because the recipe points to a non-existent tag (see variable `SRC_URI`). Additionally, no 'LICENSE' file exists in the `jmespath` repository, leading to an error when trying to build the package; so, I also updated the name of the LICENSE file (see variable `LIC_FILES_CHKSUM`)
=> fix python3-jmespath recipe to properly build ver. 0.10.0 on branch gatesgarth

recipes-support/awscli/awscli_1.19.36.bb
None
*Description of changes:* 
awscli depends on groff to format the help text. As this is a runtime dependency it doesn't cause a build failure but does result in a error when using the the utility.*
*Local Test:*
Appended awscli to my image install. Booted the image, confirmed `groff` was installed by running `groff --version`, then I ran `aws help` without an error and confirmed the help text was formatted.
=> awscli: add groff as a runtime dependency

recipes-devtools/amazon-corretto/corretto-11-bin_11.0.9.12.1.bb
Fixed SRC_URI to use the same URL in zeus as used in master.
=> Fix SRC_URI_arm for amazon-corretto (zeus)

recipes-iot/aws-iot-greengrass/README.md, recipes-iot/aws-iot-greengrass/greengrass-bin-demo_2.1.0.bb, recipes-iot/aws-iot-greengrass/greengrass-bin-demo_2.2.0.bb, recipes-iot/aws-iot-greengrass/greengrass-bin-demo_2.3.0.bb, recipes-iot/aws-iot-greengrass/greengrass-bin_2.0.3.bb, recipes-iot/aws-iot-greengrass/greengrass-bin_2.1.0.bb, recipes-iot/aws-iot-greengrass/greengrass-bin_2.2.0.bb, recipes-iot/aws-iot-greengrass/greengrass-bin_2.3.0.bb
*Issue #, if available:* N/A
*Description of changes:* 
* Adds the images for greengrass 2.1.0, 2.2.0 and 2.3.0 which were released in 2021.
* Adds sudo dependency to greengrass-bin, as it is used by AWS IoT Greengrass v2 to run components with the specified username, and also required by IoT Device Tester to qualify a Greengrass device.
=> chore(release): create Greengrass 2.1/2.2/2.3 recipes

recipes-devtools/amazon-corretto/corretto-11-bin_11.0.9.12.1.bb
*Issue #, if available:* -
I checked out the current dunfell branch and noticed it does not build greengrass v2 bin for ARM because corretto fetch sources task is failing. Cherry picked the missing commit from meta-aws master.
=> fix armv7 download for dunfell branch

recipes-sdk/aws-c-auth/aws-c-auth_0.4.9.bb, recipes-sdk/aws-c-cal/aws-c-cal_0.4.5.bb, recipes-sdk/aws-c-common/aws-c-common_0.4.67.bb, recipes-sdk/aws-c-compression/aws-c-compression_0.2.10.bb, recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.2.6.bb, recipes-sdk/aws-c-http/aws-c-http_0.5.9.bb, recipes-sdk/aws-c-io/aws-c-io_0.8.3.bb, recipes-sdk/aws-c-iot/aws-c-iot_0.0.2.bb, recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.5.5.bb, recipes-sdk/aws-c-s3/aws-c-s3_0.1.4.bb, recipes-sdk/aws-checksums/aws-checksums_0.1.11.bb, recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.11.8.bb, recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2.inc, recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.10.5.bb, recipes-sdk/aws-iot-greengrass-sdk/aws-greengrass-core-sdk-c_git.bb, recipes-sdk/s2n/s2n_0.10.26.bb
Clearing PACKAGES variable to only contain ${PN} is very bad and it's not clear
what the purpose is. It doesn't cause much trouble during the regular build for
the target, as do_populate_sysroot() is able to collect required artifacts. But
since there are no ${PN}-dev, ${PN}-dbg and ${PN}-staticdev packages produced,
it renders an SDK with AWS IoT components completely useless, especially since
majority of them only produce .a libraries.
This change removes overwriting/clearing of the PACKAGES variable to use the
default value. If it was done as a workaround for some other issue, a better
solution should be found and not this "sledgehammer approach".
Signed-off-by: Denys Dmytriyenko <denis@denix.org>
=> [dunfell] recipes-sdk: do not overwrite/clear PACKAGES variable

recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Fixes #140 
Change commit hash to https://github.com/aws-samples/aws-iot-securetunneling-localproxy/commit/b5bc3d3e250089ace65b55adf1835eab19642e45 which makes modification to boost dependency
=> build dependencies fixed - change commit hash to point to fix

recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2.inc, recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.10.5.bb, recipes-sdk/aws-iot-greengrass-sdk/aws-greengrass-core-sdk-c_git.bb
According to Debian policy, shared libraries should be versioned and named
as libNAME.so.X.Y.Z, while unversioned libNAME.so being a symlink to the
actual lib and only needed at build time, not at runtime. Hence OE normally
packages .so into ${PN}-dev and not into main ${PN}.
Allow packaging unversioned .so libraries into the main ${PN} package by
resetting FILES_SOLIBSDEV, that would otherwise let ${PN}-dev grab them and
cause this error:
QA Issue: -dev package aws-iot-device-sdk-cpp-v2-dev contains non-symlink .so '/usr/lib/libDiscovery-cpp.so'
Signed-off-by: Denys Dmytriyenko <denis@denix.org>
=> [dunfell] recipes-sdk: enable packaging of unversioned .so into ${PN}

recipes-sdk/aws-c-auth/aws-c-auth_0.6.1.bb, recipes-sdk/aws-c-cal/aws-c-cal_0.5.11.bb, recipes-sdk/aws-c-common/aws-c-common_0.6.8.bb, recipes-sdk/aws-c-compression/aws-c-compression_0.2.14.bb, recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.2.7.bb, recipes-sdk/aws-c-http/aws-c-http_0.6.5.bb, recipes-sdk/aws-c-io/aws-c-io_0.10.7.bb, recipes-sdk/aws-c-iot/aws-c-iot_0.0.7.bb, recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.6.bb, recipes-sdk/aws-c-s3/aws-c-s3_0.1.23.bb, recipes-sdk/aws-checksums/aws-checksums_0.1.11.bb, recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.15.0.bb, recipes-sdk/aws-lc/aws-lc_0.0.1.bb, recipes-sdk/s2n/s2n_1.0.13.bb
change cmake file package split target from -dbg to -dev
=> move cmake files from -dbg to -dev, fixes #179

qa/buildspec.checklayer.yml
Convert `$HOME/dist/meta-aws` to `$CODEBUILD_SRC_DIR`
Remove an option that is pulling in layercheck for meta-python. This is
out of scope for this check and instead we should rely on upstream QA.
Break the command into multiple lines to make it easier to read.
Remove a second `-d` option.
Add --no-auto, --no-auto-dependency, and convert to longer option names.
=> qa: update buildspec for dunfell

qa/buildspec.checklayer.yml
Convert `$HOME/dist/meta-aws` to `$CODEBUILD_SRC_DIR`
Remove an option that is pulling in layercheck for meta-python. This is
out of scope for this check and instead we should rely on upstream QA.
Break the command into multiple lines to make it easier to read.
Remove a second `-d` option.
Add --no-auto, --no-auto-dependency, and convert to longer option names.
=> qa: update buildspec for gatesgarth

recipes-support/awscli/awscli_1.19.36.bb, recipes-support/awscli/awscli_1.20.54.bb
The following PR contains some coding style changes in the awscli recipe, adds missing runtime dependencies and bumps the version of the awscli to the most recent 1.x.y release.
=> aws-cli: fix dependencies and bump version

recipes-devtools/amazon-corretto/corretto-17-bin_17.0.0.35.1.bb
Tested with `java -version` and using javac/java on a small hello world
application on qemux86-64 and qemuarm64.
=> corretto-17-bin: add corretto 17 bin library

recipes-iot/aws-iot-greengrass/greengrass-bin_2.4.0.bb
Here is the current Yocto zeus branch recipe for Greengrass 2.4.0 that we are using on a development IoT device. It is nearly identical to the master version, but with syntax changes and an absolute symlink change for zeus compatibility.
=> Add Greengrass 2.4.0 recipe for zeus branch

recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
fixed checksum for aarch64, armv7 and x86 (x86-64 was ok)
=> corretto 11: fixed checksum for aarch64, armv7 and x86 

recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.6.bb, recipes-sdk/aws-c-mqtt/files/fix-missing-macro.patch
Added missing AWS_MQTT_API macro in patch
=> Patch: Fix missing macro

recipes-sdk/aws-crt-python/aws-crt-python_0.13.11.bb, recipes-sdk/aws-crt-python/files/0001-fix-library-suffix.patch, recipes-sdk/aws-crt-python/files/0002-disable-building-of-depending-libs.patch, recipes-sdk/aws-lc/aws-lc_1.1.0+.bb
aws-crt-python: added a patch to disable building of depending libs, they should be used from yocto DEPENDS and build correctly for arch arm
aws-lc: removing suppression parameters, they are not necessary anymore by commit 038628d24feab1c4fce75c9b6a47bfa99b7c5edc
=> aws-crt-python, aws-lc: fix for arch arm

recipes-support/awscli/awscli_1.20.54.bb
This is a kirkstone backport of the patch accepted into master-next.
This silences the following warning:
WARNING: awscli-1.20.54-r0 do_cleanall: URL: git://github.com/aws/aws-cli.git;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
=> awscli: set branch parameter in SRC_URI

recipes-devtools/amazon-corretto/corretto-11-bin_11.0.15.9.1.bb, recipes-devtools/amazon-corretto/corretto-17-bin_17.0.3.6.1.bb
dnf, the tool used to create images when using PACKAGE_CLASSES ?= "package_rpm" will scan installed libraries
for dependencies. Since this binary jdk has libs depending on x11 or asound image creation will fail.
This commit will delete those unnecessary libraries to allow building a smaller image.
The deleted libraries are the same as when downloading a headless JRE
=> corretto-11-bin, corretto-17-bin: x11 dependency removed

recipes-devtools/amazon-corretto/corretto-11-bin_11.0.15.9.1.bb, recipes-devtools/amazon-corretto/corretto-17-bin_17.0.3.6.1.bb, recipes-devtools/amazon-corretto/corretto-8-bin_8.332.08.1.bb, recipes-iot/aws-iot-greengrass/greengrass_1.11.6.bb
A regular expression that resolves to one or more target machines with which a recipe is compatible. The regular expression is matched against MACHINEOVERRIDES. You can use the variable to stop recipes from being built for machines with which the recipes are not compatible. Stopping these builds is particularly useful with kernels. The variable also helps to increase parsing speed since the build system skips parsing recipes not compatible with the current machine.
=> corretto, greengrass: set COMPATIBLE_MACHINE

recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge.bb, recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.9.253.bb
_Description of changes:_
Updates aws-iot-fleetwise-edge recipe to the latest released version v0.1.4 of aws-iot-fleetwise-edge.
=> Update aws-iot-fleetwise-edge recipe to v0.1.4

.github/workflows/ff-merge.yml
This should configure the repo to use this token for future steps.
=> github: use bot token in checkout of ff-merge

conf/layer.conf
Description of changes:
Remove LICENSE_PATH from config after /licenses directory was deleted.
=> Remove LICENSE_PATH from config

recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge.bb
Description of changes:
Updates aws-iot-fleetwise-edge recipe to the latest released version v1.0.3 of aws-iot-fleetwise-edge. 
=> Update aws-iot-fleetwise-edge to v1.0.3

recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.582.0.bb
This commit correct spelling mistake in amazon-ssm-agent_3.2.582.0.bb. The word "enabsle" was corrected to "enable".
=> Correct spelling mistake

recipes-sdk/aws-c-common/files/run-ptest
ring_buffer_acquire_multi_threaded_test need to much memory
=> aws-c-common: disable ring_buffer_acquire_multi_threaded_test

recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_git.bb
If UPSTREAM_CHECK_COMMITS is not set it will not use the specified commit, instead it will be downgraded to the last release tag.
=> amazon-kvs-webrtc-sdk: add UPSTREAM_CHECK_COMMITS

recipes-sdk/aws-crt-python/aws-crt-python_0.16.16.bb, recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
shared lib patch is again necessary:
https://github.com/awslabs/aws-crt-python/commit/11eb2a45de915623344754a2f3bfdc2197dc5e62#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7
=> aws-crt-python: upgrade 0.16.15 -> 0.16.16, readd shared patch

recipes-sdk/aws-c-common/files/run-ptest
ctest in dunfell does not support json param, so replace by simple test
=> aws-c-common: fix ptest

recipes-sdk/aws-crt-cpp/aws-crt-cpp/run-ptest
=> aws-crt-cpp: improve ptest

recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
when building for arm64 this error persists - only on dunfell, therefore disable ptest {'amazon-kvs-producer-pic': '2023-09-18T09:25\n'
'2023-09-18T09:25\n'
'/usr/lib/amazon-kvs-producer-pic/ptest/run-ptest: '
'line 2:   375 Bus error               '
'tests/kvspic_test '
'--gtest_filter=*ClientApiTest.create* '
'--gtest_output=json:result.json > /dev/null\n'
'Traceback (most recent call last):\n'
'  File "ptest_result.py", line 11, in <module>\n'
"    with open (sys.argv[1], 'rb') as json_file:\n"
'FileNotFoundError: [Errno 2] No such file or '
"directory: 'result.json'\n"
'\n'
'ERROR: Exit status is 1\n'
'DURATION: 1\n'}
=> amazon-kvs-producer-pic: disable ptest for dunfell

recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb, recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
there are sporadic errors when enable debug split, but no value in this debug information
INHIBIT_PACKAGE_DEBUG_SPLIT = "1"
=> firecracker-bin, jailer-bin: disable debug split

recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
add LDFLAGS += "-Wl,--copy-dt-needed-entries"
=> aws-iot-securetunneling-localproxy: fix DSO missing from command line

recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
by greengrass-bin, cause greengrass-bin-demo was causing issues when an image contained greengrass-bin and an SDK was built.
=> greengrass-bin_2.9.6.bb: replace ptest RDEPENDS greengrass-bin-demo

recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.bb
fixed: https://github.com/awslabs/aws-iot-device-client/issues/411
=> aws-iot-device-client: readd, upgrade 1.8. -> 1.9.

recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb, recipes-iot/aws-iot-securetunneling-localproxy/files/boost-support-any.patch, recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13.patch
This reverts commit 2027a50c986b279bf52bfa366e3c9fc66b390378.
This release needs a patch for missing declarations
=> Revert "aws-iot-securetunneling-localproxy: upgrade git -> new"

recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb, recipes-iot/aws-iot-securetunneling-localproxy/files/remove-cxx-standard.patch
This is because abseil is compiled with default cxx-standard of the compiler, and needs to be the same.
=> aws-iot-securetunneling-localproxy: remove setting of cxx-standard

recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.1.0.bb, recipes-iot/aws-iot-fleetwise/files/remove-cxx-standard.patch
This is because abseil is compiled with default cxx-standard of the compiler, and needs to be the same.
=> aws-iot-fleetwise-edge: remove setting of cxx-standard

recipes-devtools/amazon-corretto/corretto-11-bin/run-ptest, recipes-devtools/amazon-corretto/corretto-11-bin_11.0.21.9.1.bb, recipes-devtools/amazon-corretto/corretto-17-bin/run-ptest, recipes-devtools/amazon-corretto/corretto-17-bin_17.0.9.8.1.bb, recipes-devtools/amazon-corretto/corretto-21-bin/run-ptest, recipes-devtools/amazon-corretto/corretto-21-bin_21.0.1.12.1.bb, recipes-devtools/amazon-corretto/corretto-8-bin/run-ptest, recipes-devtools/amazon-corretto/corretto-8-bin_8.392.08.1.bb, recipes-devtools/amazon-corretto/corretto-bin-common.inc
meta-aws-test is searching for ptest in bb file to find recipes to test, therefor move inherit ptest into recipe
running ptest in testimage require all recipes to install in parallel, so ALTERNATE mechanism is added
=> corretto-8,11,17,21-bin: add alternate name, fix ptest

recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.bb
Related to issue https://github.com/awslabs/aws-iot-device-client/issues/411
Based on comments in https://github.com/awslabs/aws-iot-device-client/issues/411#issuecomment-1867735644 issues with secure tunneling in https://github.com/awslabs/aws-iot-device-client/issues/411 were resolved in 1.19, however the "st" package config wasn't added back in with https://github.com/aws4embeddedlinux/meta-aws/commit/80c74bfdeafef4fb8a32604b72c347a592469e46.
I've verified this configuration works with secure tunneling using the kas config at https://github.com/Trellis-Logic/meta-aws-iot-demo/blob/main/conf/kas/rpi-rauc-aws-master.yml as well as the kirkstone branch at https://github.com/Trellis-Logic/meta-aws-iot-demo/blob/main/conf/kas/rpi-rauc-aws.ym …
=> aws-iot-client: add secure tunnel back in

recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.291.bb
Add '###' to close the commented lines. Fixes the bitbake parsing error caused by the trailing backslash:
ERROR: ParseError at meta-aws/recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.291.bb:430:
Unparsed lines: ['# ec2;', '# s3-encryption;', '# identity-management;']
ERROR: Parsing halted due to errors, see error messages above
=> aws-sdk-cpp: fix the ParseError

recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.299.bb
Introduced by: https://github.com/aws/aws-sdk-cpp/commit/6caa146a3dcbee72111fc81e6c48473d4836e280
```
include(GoogleTest)
gtest_discover_tests(${PROJECT_NAME})
```
leads to
GoogleTestAddTests.cmake
| .../build/tests/aws-cpp-sdk-s3-unit-tests/aws-cpp-sdk-s3-unit-tests: error while loading shared libraries: libaws-crt-cpp.so: cannot open shared object file: No such file or directory
-> fix is to use cmake-qemu class instead of cmake
=> aws-sdk-cpp: upgrade 1.11.291 -> 1.11.299, cmake-qemu

recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.319.bb
This is possible by this commit:
https://github.com/aws/aws-sdk-cpp/commit/c359cb6f2b659ce4c3f212d991e1f1b05dd92302
Will allow backports to kirkstone again.
=> aws-sdk-cpp: use cmake instead of cmake-qemu

conf/machine/aws-ec2-arm64.conf, scripts/ec2-ami/create-ec2-ami.sh
Based on suggestions from Jan-Simon Moeller.
- Fixing a potential race by adding, that caused bootloader not in place, when generating the image.
WKS_FILE_DEPENDS_BOOTLOADERS:aarch64 += "systemd-boot"
- Using bitbake-getvar to get DEPLOY_DIR_IMAGE cause build and tmp dir can have various names.
=> EC2-AMI feature: fix race, get var

scripts/ec2-ami/create-ec2-ami.sh
This adds a example commandline and also checks for the AMI_DISK_SIZE being only and integer.
=> Add example to help and check for correct AMI_DISK_SIZE_GB

recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.6.bb
${GG_ROOT}/alts/init/distro must be a symbolic link to /${GG_BASENAME}/packages/artifacts-unarchived/aws.greengrass.Nucleus/${PV}/aws.greengrass.nucleus
=> greengrass-bin: fix directory link, version upgrade 2.12.5 -> 2.12.6

recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.6.bb
As java 11 is still the default for greengrass and Corretto 11 is under LTS:
https://aws.amazon.com/de/about-aws/whats-new/2020/08/amazon-corretto-8-11-support-extended/
Also helps here: https://github.com/aws4embeddedlinux/meta-aws/commit/cc8ab6c5e3a6ec500a1aa69b74cc0ef3bb5fb0e6#commitcomment-143921769
=> greengrass set jvm java 11default

recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb, recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning/run-ptest, recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.6.bb
=> aws-iot-device-sdk-cpp-v2: add fleet provisoning example

recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/global-thread-sleep-linkerror.patch, recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.4.1.bb
fix https://github.com/aws4embeddedlinux/meta-aws/issues/1701
=> amazon-kvs-producer-sdk-cpp: fix globalThreadSleep link error

recipes-sdk/aws-crt-python/files/run-ptest
This test is failing a expected exception is thrown causing ptest to fail
=> aws-crt-python: disable test_websocket.py unit test

recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.6.bb
new version of greengrass-bin changed path of loader, patch failed. Also update sha of aws.greengrass.FleetProvisioningByClaim.jar latest.
fix #9501
=> greengrass-bin: fix fleetprovisioning

recipes-sdk/s2n/s2n/run-ptest
=> s2n: disable s2n_aead_aes_test as it fails in docker

recipes-sdk/s2n/s2n/run-ptest
=> s2n: disable ptest s2n_stacktrace_test as it is not running in container

.github/workflows/auto-recipe-update.yml, .github/workflows/build-test-recipe.yml
=> 2024 11 18 master next fix fork point

recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.451.bb
(cherry picked from commit b02f05847d6a396326d71fcb460ab0c7cb5a99d9)
*Issue:*
#10437
Backports recent updates of `aws-sdk-cpp`. The automatic backport mechanism currently appears to be experiencing issues, so this update has been manually cherry-picked.
=> [Backport scarthgap-next] aws-sdk-cpp: upgrade 1.11.432 -> 1.11.451

recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.11.0.bb
INSANE_SKIP:${PN}-ptest += "expanded-d" seems to be obsolete.
=> amazon-kvs-webrtc-sdk: remove INSANE_SKIP expanded-d

.github/workflows/build-test-recipe.yml
=> build-test-recipe.yml: fix getting changed recipes from a fork

.github/workflows/build-test-all-branches.yml, .github/workflows/build-test-recipe.yml, .github/workflows/ff-merge.yml
=> github workflows: backport from master-next

recipes-iot/aws-iot-greengrass/greengrass-lite/run-ptest, recipes-iot/aws-iot-greengrass/greengrass-lite_2.0.0.bb
Disable automatic startup of gg-lite, cause this will use the same port as greengrass-bin, conflicting.
=> greengrass-lite: fix ptest for greengrass-bin

recipes-devtools/amazon-corretto/corretto-11-bin/run-ptest, recipes-iot/aws-iot-greengrass/greengrass-bin_2.14.0.bb, recipes-iot/aws-iot-greengrass/greengrass-lite_2.0.0.bb
=> greengrass-bin: fix ptest, by disable use in corretto-11-bin

recipes-iot/aws-iot-greengrass/greengrass-bin_2.14.0.bb
*Issue #, if available:* 10914
*Description of changes:* Changes mode of 'loader' from 640 to 750 so that it can be executed in Greengrass bin
=> Fix issue 10914: changed loader mode from 640 to 750

recipes-containers/firecracker-bin/firecracker-bin_1.10.1.bb, recipes-containers/firecracker-bin/jailer-bin_1.10.1.bb
OE-Core changed to to use virtual/cross-binutils to replace the older more complex cross providers. Update the recipes to match.
This fixes check layer failures on the autobuilder.
=> firecracker-bin: Update to match OE-Core virtual provider changes

recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/001-cmake-aws-module-path.patch, recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.34.0.bb
Breaking change in CMAKE file of CRT libs.
https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/776
=> aws-iot-device-sdk-cpp-v2: fix build with latest CRT

recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.506.bb
Done because of compile issues in kirkstone branch. Like this:
| {standard input}: Assembler messages:
| {standard input}:6107201: Warning: end of file not at end of a line; newline inserted | {standard input}:6108273: Error: unknown pseudo-op: `.lbe1711249' | {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive | x86_64-poky-linux-g++: fatal error: Killed signal terminated program cc1plus | compilation terminated.
=> aws-sdk-cpp: disable sanitizers

.github/workflows/build-test-recipe.yml
As there are issues with this feature in kirkstone. Like: 
...vmap allocation for size 1052672 failed: use vmalloc=<size> to increase size\n[    3.926648] pci-host-generic 3f000000.pcie: ECAM ioremap failed\n[    3.927917] pci-host-generic: probe of 3f000000.pcie failed with error -12\n[    3.957702] printk: console [hvc0] enabled\n[    3.987493] brd: module loaded\n[    3.999732] virtio_blk virtio1: [vda] 981384 512-byte logical blocks (502 MB/479 MiB)\n
=> build-test-recipe.yml: disable parselogs for kirkstone

.github/workflows/build-test-all-branches.yml
Since activating sanitizers tests run longer.
=> build-test-all-branches.yml: wait up to 5h

.github/workflows/build-test-recipe.yml
As it does not build a version for arm32.
=> build-test-recipe.yml: disable amazon-cloudwatch-agent arm32 ptest

.github/workflows/build-test-recipe.yml, recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc, recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.35.1.bb
build-deps is enabled by default to use the aws-c-iot lib (and its dependencies) version that comes as a git submodule, this also means that it conflicts with the aws-c-iot as it installs the same library if installed separate.
This was done because of https://github.com/awslabs/aws-iot-device-client/issues/502
=> aws-iot-device-sdk-cpp-v2: change to use build-deps

recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.35.1.bb
to fix textrel error on arm32 in styhead.
=> aws-iot-device-sdk-cpp-v2: add PIC

recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb, recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning/run-ptest
From fleet-provisioning to aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning, as there is a name conflict with greengrass-bin fleet-provisioning.
=> aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning: rename binary

recipes-iot/aws-iot-greengrass/greengrass-lite_2.0.2.bb
By setting gg_workingdir:pn-greengrass-lite = "xxx" in the local conf it is easy possible to change the workdir location.
=> greengrass-lite: remove not used gg_rundir, allow gg_workdir overrides

recipes-support/aws-cli-v2/aws-cli-v2_2.27.0.bb
=> aws-cli-v2: fix warning whitespace missing around assignement

recipes-iot/aws-iot-greengrass/greengrass-bin_2.14.1.bb
Without this bbappends like here:
https://github.com/aws4embeddedlinux/meta-aws-demos/blob/fb51b404a23a329f4b0a52fadc47ee7609f9062c/meta-aws-demos/recipes-iot/aws-iot-greengrass/greengrass-bin_%25.bbappend#L5 do not work anymore.
=> greengrass-bin: change subdir structure to fix bbappends

recipes-sdk/aws-crt-cpp/aws-crt-cpp/001-shared-static-crt-libs.patch, recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.32.5.bb
As it is not guarnteed that depending libs if they are build separate are fully compatible.
=> aws-crt-cpp: change to build-deps as default

.github/workflows/build-test-recipe.yml
This bug: https://github.com/awslabs/aws-c-common/issues/1204
=> aws-c-common: disable tests for arm32

.github/workflows/build-test-recipe.yml
known issue:
https://github.com/awslabs/aws-c-common/issues/1204
=> build-test-recipe.yml: disable aws-crt-cpp tests on arm32

.github/workflows/build-test-recipe.yml
As there a some "not enough memory for the allocation" errors.
=> build-test-recipe.yml: make QB_MEM 8GB default

recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
The version of recipe aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub is `1.0' $ ls tmp/work/corei7-64-wrs-linux/aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub/ 1.0
Because no PV in recipe, and use 1.0 as default
Due to recipe aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub and aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning use the same source of aws-iot-device-sdk-cpp-v2
...
aws-iot-device-sdk-cpp-v2-version.inc <-- aws-iot-device-sdk-cpp-v2-samples.inc <-- aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub.bb aws-iot-device-sdk-cpp-v2-version.inc <-- aws-iot-device-sdk-cpp-v2-samples.inc <-- aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb ...
Explicitly set PV in aws-iot-device-sdk-cpp-v2-version.inc
After apply this patch:
$ ls …
=> aws-iot-device-sdk-cpp-v2-version.inc: explicitly set PV

recipes-iot/aws-iot-device-client/aws-iot-device-client_1.10.1.bb, recipes-iot/aws-iot-device-client/files/002-set-cmake-min-version-for-external-project-sdk-and-src-path.patch
BUILD_SDK=ON as default
aws-iot-device-sdk-cpp-v2 needs to be 1.30.3 otherwise: "While other versions of the aws-iot-device-sdk-cpp-v2 may work,
it is highly recommended that the specified commit is used."
and static because installing shared libs from this seems wrong.
closes #13012
=> aws-iot-device-client: BUILD_SDK=ON static by default

recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.32.5.bb
Build aws-crt-cpp failed for qemuriscv64
$ echo 'MACHINE = "qemuriscv64-64"' >> conf/local.conf $ bitbake aws-crt-cpp
...
|/usr/src/debug/openssl/3.4.1/crypto/aes/aes-riscv64.s:972:(.text+0x946): relocation truncated to fit: R_RISCV_JAL against symbol `AES_set_encrypt_key' defined in .text section in tmp/work/riscv64-wrs-linux/aws-crt-cpp/0.32.5/recipe-sysroot/usr/lib/libcrypto.a(libcrypto-lib-aes-riscv64.o) ...
Explicitly add static to PACKAGECONFIG for riscv64
=> aws-crt-cpp: workaround compile failure for qemuriscv64

recipes-sdk/corehttp/corehttp_3.1.1.bb, recipes-sdk/coremqtt/coremqtt_2.3.1.bb, recipes-sdk/corepkcs11/corepkcs11_3.6.3.bb, recipes-sdk/device-defender-for-aws-iot-embedded-sdk/device-defender-for-aws-iot-embedded-sdk_1.4.0.bb, recipes-sdk/device-shadow-for-aws-iot-embedded-sdk/device-shadow-for-aws-iot-embedded-sdk_1.4.1.bb, recipes-sdk/fleet-provisioning-for-aws-iot-embedded-sdk/fleet-provisioning-for-aws-iot-embedded-sdk_1.2.1.bb, recipes-sdk/linux-webrtc-reference-for-amazon-kinesis-video-streams/linux-webrtc-reference-for-amazon-kinesis-video-streams_git.bb, recipes-sdk/sigv4/sigv4_1.3.0.bb
corehttp
coremqtt
corepkcs11
device-defender-for-aws-iot-embedded-sdk
device-shadow-for-aws-iot-embedded-sdk
fleet-provisioning-for-aws-iot-embedded-sdk
linux-webrtc-reference-for-amazon-kinesis-video-streams sigv4
=> fix arm32 builds for embedded-c libs, append instead of replace CFLAGS

recipes-sdk/aws-crt-python/aws-crt-python_0.27.4.bb, recipes-sdk/aws-crt-python/files/001-fix-cross-compilation-support.patch
Instead of separate packages as they are might not compatible.
=> aws-crt-python: use submodule version of crt libs

.github/workflows/yocto-check-layer.yml
systemd is enabled as greengrass-lite requires this and thus yocto-check-layer is failing
=> yocto-check-layer.yml: replace deprecated set-output, enable systemd

recipes-containers/firecracker-bin/firecracker-bin_1.10.1.bb, recipes-containers/firecracker-bin/jailer-bin_1.10.1.bb
As this is not necessary on kirkstone
=> firecracker-bin, jailer-bin: remove virtual/cross-binutils dep

recipes-sdk/aws-c-common/aws-c-common_0.12.4.bb, recipes-sdk/aws-c-common/files/0001-skip-iso8601-tests-on-32bit.patch
=> aws-c-common: disable date time tests on arm32

recipes-sdk/aws-crt-python/aws-crt-python_0.27.6.bb
Some test scripts in ptest still use `#!/usr/bin/python`, which may not be available on modern systems where only `python3` is installed. This change updates the shebang line in all ptest test scripts to use `#!/usr/bin/python3` to ensure compatibility.
Affected files include (but are not limited to):
- aws-lc/util/generate-asm-lcov.py
- s2n/tests/sidetrail/bin/bpl_trace_to_c.py
=> aws-crt-python: update ptest shebang to use python3

recipes-sdk/aws-crt-python/aws-crt-python_0.27.6.bb, recipes-sdk/aws-crt-python/files/001-fix-cross-compilation-support.patch, recipes-sdk/aws-crt-python/files/002-revert-bdist-wheel.patch
(cherry picked from commit c4d1e146009bb98dc161e3d30688a145e77efbd3)
Add 002-revert-bdist-wheel.patch as we use an older version of setuptools
=> aws-crt-python: upgrade 0.27.4 -> 0.27.6

recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb, recipes-iot/aws-iot-securetunneling-localproxy/files/0005-fix-boost-system-header-only.patch
=> aws-iot-securetunneling-localproxy: compatibe with Boost 1.89.0
