- conf/layer.conf
- recipes-greengrass/greengrass-core/greengrass_1.10.0.bb
- Updated layer config version compatibility to latest Yocto release
- Updated greengrass-core version number and hashes
> Updated to latest Yocto and greengrass-core releases

- recipes-greengrass/greengrass-core-sdk/aws-greengrass-core-sdk-python_git.bb
- Created recipe to install greengrass-core-sdk-python to /greengrass
> Created recipe to install greengrass-core-sdk-python

- conf/layer.conf
> only support zeus on this branch

- recipes-greengrass/greengrass-core/greengrass.inc
> Use Python 3 modules + fixes

- recipes-crt/aws-crt-python/aws-crt-python.inc
- recipes-crt/aws-crt-python/aws-crt-python_0.5.11.bb
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2.inc
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_git.bb
> WIP: aws-iot-device-sdk-python-v2

- recipes-crt/aws-crt-python/aws-crt-python.inc
- recipes-crt/aws-crt-python/aws-crt-python_0.5.11.bb
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2.inc
Issue: #40 
Further work on the aws-iot/aws-crt python recipes.
This now builds and runs the `samples/pubsub.py` fine:
```
Subscribing to topic 'samples/test'...
Subscribed with QoS.AT_LEAST_ONCE
Sending 10 message(s)
Publishing message to topic 'samples/test': Hello World! [1]
Received message from topic 'samples/test': b'Hello World! [1]'
Publishing message to topic 'samples/test': Hello World! [2]
Received message from topic 'samples/test': b'Hello World! [2]'
Publishing message to topic 'samples/test': Hello World! [3]
Received message from topic 'samples/test': b'Hello World! [3]'
Publishing message to topic 'samples/test': Hello World! [4]
Received message from topic 'samples/test': b'Hello World! [4]'
Publishing message to topic 'samples/test': Hello World! [5]
Received message …
```
> aws-iot-device-sdk-python-v2

- conf/layer.conf
Signed-off-by: Codrin Ciubotariu <codrin.ciubotariu@microchip.com>
> layer.conf: Mark master as dunfell (3.1) compatible

- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.5.2.bb
Signed-off-by: Codrin Ciubotariu <codrin.ciubotariu@microchip.com>
*Description of changes:* Some fixes for the aws-iot-device-sdk-cpp-v2 recipe. aws-iot-device-sdk-v2.inc is still missing though.
> sdk-cpp: Recipe parse fixes

- recipes-greengrass/greengrass-core/greengrass_1.10.1.bb
Issue #60 
added patchelf for greengrassSystemComponents
> add patchelf for greengrassSystemComponents

- recipes-sdk/aws-iot-device-sdk-python-v1/aws-iot-device-sdk-python-v1.inc
- recipes-sdk/aws-iot-device-sdk-python-v1/aws-iot-device-sdk-python-v1_git.bb
Add recipe aws-iot-device-sdk-python-v1. Not sure if anything else needs to be added.
Resolves #39 
> feat: add recipe aws-iot-device-sdk-python-v1

- recipes-greengrass/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Signed-off-by: Arnstein Kleven <arnsteinkleven@gmail.com>
Couldn't find this on warrior branch. Snatched the one from master and seems to work well with my system running warrior.
This is the same recipe as found on meta-aws master branch.
> Add aws-iot-securetunneling-localproxy

- conf/layer.conf
- recipes-greengrass/greengrass-core-sdk/aws-greengrass-core-sdk-c_git.bb
> Home gihub/master

- recipes-devtools/amazon-sagemaker-neo/README.md
- recipes-devtools/amazon-sagemaker-neo/neo-ai-dlr_1.7.0.bb
- recipes-external/python3/python3-distro_1.5.0.bb
**Issue #, if available:**
Fixes https://github.com/aws/meta-aws/issues/95
**Description of changes:**
Added python3-distro package to zeus as an external recipe
> Add python3-distro to Dunfell

- recipes-devtools/amazon-sagemaker-neo/README.md
- recipes-devtools/amazon-sagemaker-neo/neo-ai-dlr_1.7.0.bb
- recipes-external/python3/python3-distro_1.5.0.bb
**Issue #, if available:**
Fixes #95
**Description of changes:**
Added python3-distro package to zeus as an external recipe
> Add python3-distro dependency to Zeus

- recipes-crt/aws-crt-python/aws-crt-python.inc
Related to https://github.com/aws/meta-aws/issues/104. The pull request is for Dunfell branch, but porting the changes to master and zeus should work.
Change branch from master to main
> aws-crt-python: Change master branch for main branch

- recipes-devtools/amazon-sagemaker-neo/neo-ai-dlr_1.4.0.bb
- recipes-devtools/amazon-sagemaker-neo/neo-ai-dlr_1.7.0.bb
N/A
Neo Repository follows new D&I guidance master--> main. Changed recipe to correct target branch.
Tested on i.MX8mqevk.
> Update Neo AI DLR recipe with correct branch

- recipes-iot/aws-iot-greengrass/files/greengrass.conf
- recipes-iot/aws-iot-greengrass/greengrass.inc
- recipes-iot/aws-iot-greengrass/greengrass_1.10.0.bb
- recipes-iot/aws-iot-greengrass/greengrass_1.10.1.bb
- recipes-iot/aws-iot-greengrass/greengrass_1.11.0.bb
Updating the dunfell branch with the #103 patch.
> fix: applying issue #103 patch to dunfell branch

- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.0.1.bb
- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.1.0.bb
- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.2.0.bb
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2.inc
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.10.5.bb
> Remove PACKAGES override remnants

- qa/repo.checklayer.hardknott.xml
N/A
Add repo configuration for hardknott QA check
> add checks for new release hardknott

- qa/buildspec.checklayer.yml
- qa/checklayer/conf/bblayers.conf
None
Modify layer checks to reflect YP changes to yocto-check-layer for dependencies.
> fix bblayers and command line for new dependency check changes

- recipes-iot/aws-iot-greengrass/greengrass-bin-demo_2.0.3.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin-demo_2.1.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin-demo_2.2.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin-demo_2.3.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin-demo_2.4.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.4.0.bb
Make `dunfell` syntax consistent with itself.
> fix: make dunfell recipe syntax consistent

- recipes-iot/aws-iot-greengrass/greengrass-bin-demo_2.1.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin-demo_2.2.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin-demo_2.3.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.1.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.2.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.3.0.bb
- recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
- recipes-iot/aws-iot-securetunneling-localproxy/files/0001-patch-dependency-versions.patch
> rebasing gatesgarth-next

- qa/buildspec.checklayer.yml
- qa/checklayer/conf/bblayers.conf
- qa/repo.checklayer.xml
> qa: cleanup checklayer configs and buildspec

- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.4.0.bb
- recipes-iot/aws-iot-device-client/files/01-missing-thread-includes.patch
- recipes-iot/aws-iot-device-client/files/02-missing-thread-includes.patch
- recipes-sdk/aws-c-auth/aws-c-auth_0.6.1.bb
- recipes-sdk/aws-c-cal/aws-c-cal_0.5.11.bb
- recipes-sdk/aws-c-common/aws-c-common_0.6.8.bb
- recipes-sdk/aws-c-compression/aws-c-compression_0.2.14.bb
- recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.2.7.bb
- recipes-sdk/aws-c-http/aws-c-http_0.6.5.bb
- recipes-sdk/aws-c-io/aws-c-io_0.10.7.bb
- recipes-sdk/aws-c-iot/aws-c-iot_0.0.7.bb
- recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.6.bb
- recipes-sdk/aws-c-s3/aws-c-s3_0.1.23.bb
- recipes-sdk/aws-checksums/aws-checksums_0.1.11.bb
- recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.15.0.bb
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.14.1.bb
- recipes-sdk/aws-lc/aws-lc_0.0.1.bb
- recipes-sdk/s2n/files/0001-cmakelists-remove-warn.patch
- recipes-sdk/s2n/files/0002-cmakelists-remove-warn.patch
- recipes-sdk/s2n/s2n_1.0.13.bb
Device Client, SDK C++, CRT upgrades
> Update dunfell to updated CRT C++, SDK C++, and Device Client

- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.4.0.bb
- recipes-iot/aws-iot-device-client/files/01-missing-thread-includes.patch
- recipes-iot/aws-iot-device-client/files/02-missing-thread-includes.patch
- recipes-sdk/aws-c-auth/aws-c-auth_0.6.1.bb
- recipes-sdk/aws-c-cal/aws-c-cal_0.5.11.bb
- recipes-sdk/aws-c-common/aws-c-common_0.6.8.bb
- recipes-sdk/aws-c-compression/aws-c-compression_0.2.14.bb
- recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.2.7.bb
- recipes-sdk/aws-c-http/aws-c-http_0.6.5.bb
- recipes-sdk/aws-c-io/aws-c-io_0.10.7.bb
- recipes-sdk/aws-c-iot/aws-c-iot_0.0.7.bb
- recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.6.bb
- recipes-sdk/aws-c-s3/aws-c-s3_0.1.23.bb
- recipes-sdk/aws-checksums/aws-checksums_0.1.11.bb
- recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.15.0.bb
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.14.1.bb
- recipes-sdk/aws-lc/aws-lc_0.0.1.bb
- recipes-sdk/s2n/files/0001-cmakelists-remove-warn.patch
- recipes-sdk/s2n/files/0002-cmakelists-remove-warn.patch
- recipes-sdk/s2n/s2n_1.0.13.bb
patches pulled down from master-next for update to CRT C++, Device SDK C++ V2, IoT Device Client
> Update gatesgarth latest  CRT C++, Device SDK C++ V2, IoT Device Client

- qa/buildspec.checklayer.yml
- qa/checklayer/conf/bblayers.conf
- qa/repo.checklayer.xml
- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.4.0.bb
- recipes-iot/aws-iot-device-client/files/02-missing-thread-includes.patch
- recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
- recipes-iot/aws-iot-securetunneling-localproxy/files/0001-patch-dependency-versions.patch
- recipes-sdk/aws-c-auth/aws-c-auth_0.6.1.bb
- recipes-sdk/aws-c-cal/aws-c-cal_0.5.11.bb
- recipes-sdk/aws-c-common/aws-c-common_0.6.8.bb
- recipes-sdk/aws-c-compression/aws-c-compression_0.2.14.bb
- recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.2.7.bb
- recipes-sdk/aws-c-http/aws-c-http_0.6.5.bb
- recipes-sdk/aws-c-io/aws-c-io_0.10.7.bb
- recipes-sdk/aws-c-iot/aws-c-iot_0.0.7.bb
- recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.6.bb
- recipes-sdk/aws-c-s3/aws-c-s3_0.1.23.bb
- recipes-sdk/aws-checksums/aws-checksums_0.1.11.bb
- recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.15.0.bb
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.14.1.bb
- recipes-sdk/aws-lc/aws-lc_0.0.1.bb
- recipes-sdk/s2n/files/0002-cmakelists-remove-warn.patch
- recipes-sdk/s2n/s2n_1.0.13.bb
> Update hardknott to latest CRT C++, Device SDK C++ v2, IoT Device Client

- recipes-sdk/aws-crt-python/aws-crt-python_0.12.1.bb
- recipes-sdk/aws-crt-python/files/fix-library-suffix.patch
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.7.0.bb
> upgrade support for CRT Python and Device SDK Python v2

- recipes-sdk/aws-crt-python/aws-crt-python_0.12.1.bb
- recipes-sdk/aws-crt-python/files/fix-library-suffix.patch
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.7.0.bb
> upgrade support for aws iot device sdk python v2

- recipes-sdk/aws-c-auth/aws-c-auth_0.6.1.bb
- recipes-sdk/aws-c-cal/aws-c-cal_0.5.11.bb
- recipes-sdk/aws-c-common/aws-c-common_0.6.8.bb
- recipes-sdk/aws-c-compression/aws-c-compression_0.2.14.bb
- recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.2.7.bb
- recipes-sdk/aws-c-http/aws-c-http_0.6.5.bb
- recipes-sdk/aws-c-io/aws-c-io_0.10.7.bb
- recipes-sdk/aws-c-iot/aws-c-iot_0.0.7.bb
- recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.6.bb
- recipes-sdk/aws-c-s3/aws-c-s3_0.1.23.bb
- recipes-sdk/aws-checksums/aws-checksums_0.1.11.bb
- recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.15.0.bb
- recipes-sdk/aws-lc/aws-lc_0.0.1.bb
- recipes-sdk/s2n/s2n_1.0.13.bb
change cmake file package split target from -dbg to -dev
> Gatesgarth next

- qa/buildspec.checklayer.yml
- qa/repo.checklayer.dunfell.xml
- qa/repo.checklayer.gatesgarth.xml
- qa/repo.checklayer.hardknott.xml
- qa/repo.checklayer.master.xml
- qa/repo.checklayer.sumo.xml
- qa/repo.checklayer.thud.xml
- qa/repo.checklayer.warrior.xml
- qa/repo.checklayer.zeus.xml
Pull in QA changes from hardknott
> Pull in QA updates from hardknott and update repo manifests

- recipes-devtools/python/python3-boto3_1.18.48.bb
- recipes-devtools/python/python3-botocore_1.21.48.bb
- recipes-devtools/python/python3-s3transfer_0.5.0.bb
Update boto3, botocore, and s3transfer to the latest.
> boto: update boto3 and dependencies

- recipes-devtools/amazon-corretto/corretto-8-bin_8.275.01.1.bb
- recipes-devtools/amazon-corretto/corretto-8-bin_8.302.08.1.bb
> Update corretto-8-bin version.

- recipes-devtools/amazon-corretto/corretto-8-bin_8.275.01.1.bb
- recipes-devtools/amazon-corretto/corretto-8-bin_8.302.08.1.bb
> Hardknott update corretto 8 bin

- recipes-devtools/amazon-corretto/corretto-8-bin_8.275.01.1.bb
- recipes-devtools/amazon-corretto/corretto-8-bin_8.302.08.1.bb
> Master update corretto 8 bin

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
Update Corretto 11 to 11.0.12.7.1
> Gatesgarth update Corretto 11

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
> Corretto 11: fixed checksum for aarch64, armv7 and x86 (x86-64 was ok)

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
> fixed checksum for aarch64, armv7 and x86 (x86-64 was ok)

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.0.35.1.bb
> Add java rdepends

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.0.35.1.bb
> Dunfell update corretto checksums

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.0.35.1.bb
> Gatesgarth update corretto checksums

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.0.35.1.bb
> Hardknott update corretto checksums

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.0.35.1.bb
> Dunfell next

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.0.35.1.bb
- recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.6.bb
- recipes-sdk/aws-c-mqtt/files/fix-missing-macro.patch
> Release master-next into master

- qa/repo.checklayer.honister.xml
> repocheck: add honister manifest

- recipes-cloud/amazon-cloudwatch-publisher/amazon-cloudwatch-publisher_1.2.2.bb
- recipes-devtools/amazon-sagemaker-neo-tvm/neo-ai-tvm.bb
- recipes-sdk/aws-c-cal/aws-c-cal_0.4.5.bb
- recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.2.6.bb
- recipes-sdk/aws-c-http/aws-c-http_0.5.9.bb
- recipes-sdk/aws-c-io/aws-c-io_0.8.3.bb
- recipes-sdk/aws-c-iot/aws-c-iot_0.0.2.bb
- recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.5.5.bb
- recipes-sdk/aws-c-s3/aws-c-s3_0.1.4.bb
- recipes-sdk/aws-crt-python/aws-crt-python.inc
- recipes-sdk/aws-crt-python/aws-crt-python_0.10.3.bb
- recipes-sdk/aws-crt-python/aws-crt-python_0.12.1.bb
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.5.4.bb
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.7.0.bb
- recipes-sdk/aws-iot-greengrass-sdk/aws-greengrass-core-sdk-python.inc
> aws-iot-device-sdk-python-v2: fix syntax issue

- .github/CODEOWNERS
- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.0.35.1.bb
> Release Gatesgarth

- .github/CODEOWNERS
- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.0.35.1.bb
> Release Hardknott

- recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.6.bb
- recipes-sdk/aws-c-mqtt/files/fix-missing-macro.patch
The problem described and fixed in https://github.com/aws/meta-aws/issues/234 still occurs on dunfell. Backport the relevant changes.
> Backport fixes for issue #234 to dunfell 

- recipes-devtools/amazon-sagemaker-neo/files/0002-CMakeLists_remove_test_file_downloads.patch
- recipes-devtools/amazon-sagemaker-neo/neo-ai-dlr_1.10.0.bb
- recipes-devtools/amazon-sagemaker-neo/neo-ai-dlr_1.7.0.bb
Modified patch to work with 1.10.0 recipe.
Upgraded Neo to 1.10.0
> Upgraded neo to 1.10.0

- qa/repo.checklayer.honister.xml
- recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Add branch parameter to recipe to remove warnings.
> iot: add branch parameter to securetunneling recipe

- recipes-support/amazon-ssm-agent/amazon-ssm-agent_git.bb
> ssm: add amazon ssm agent recipe

- qa/checklayer/conf/local.conf
> qa: remove image-prelink

- recipes-iot/aws-iot-greengrass/greengrass-bin_2.1.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.2.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.3.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.4.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.5.0.bb
*Issue #, if available:* #163
*Description of changes:* Added existing versions of greengrass to hardknott-next branch. Also included the fix for #269 on this branch.
> chore(release). Add greengrass versions to hardknott

- recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.9.191.bb
- recipes-sdk/aws-sdk-cpp/files/0001-build-don-t-use-Werror.patch
- recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Add a recipe for the S3 gstreamer plugin and another one to satisfy its dependency on the C++ SDK.
> Add support for the AWS S3 gstreamer plugin

- recipes-iot/aws-iot-greengrass/greengrass-bin_2.5.3.bb
*Issue #, if available:* N/A
*Description of changes:* This is our standard issue updated to 2.5.3 on gatesgarth version. 
> chore(release). Add Greengrass 2.5.3 recipe to Gatesgarth

- .github/CODEOWNERS
- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.0.35.1.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.5.3.bb
1/ Add new version of Greengrass
2/ Add changes for Corretto
> Merge Gatesgarth changes

- recipes-sdk/aws-c-common/aws-c-common_0.6.8.bb
- recipes-sdk/aws-c-common/files/ptest_result.py
- recipes-sdk/aws-c-common/files/run-ptest
> aws-c-common: add ptest run of repo tests

- qa/buildspec.checklayer.yml
Adding the license upsets the signature check.
> qa: disable signature check for this layer.

- recipes-devtools/python/python3-boto3_1.21.44.bb
- recipes-devtools/python/python3-botocore_1.24.44.bb
- recipes-devtools/python/python3-s3transfer_0.5.2.bb
python3-boto3 1.17.54 -> 1.21.44
python3-botocore 1.20.54 -> 1.24.44
python3-s3transfer 0.4.0 -> 0.5.2
> python3-boto3, python3-botocore, python3-s3transfer: bump versions

- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.6.bb
- recipes-iot/aws-iot-device-client/files/01-missing-thread-includes.patch
- recipes-iot/aws-iot-device-client/files/02-missing-thread-includes.patch
- recipes-iot/aws-iot-device-client/files/03-serviced-config.patch
- also fix dbg package generation
- config dir permissions
> aws-iot-device-client: bump version 1.4.0 -> 1.6

- recipes-sdk/aws-crt-python/aws-crt-python_0.12.1.bb
- recipes-sdk/aws-iot-device-sdk-python-v1/aws-iot-device-sdk-python-v1_git.bb
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.5.4.bb
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.7.0.bb
Signed-off-by: Rengifo, Rodrigo <rodrigo.rengifo@artrhex.com>
>  removed pv variable as it was causing the wrong recipes to be used

- conf/layer.conf
- licenses/ASL-1.0
- recipes-iot/aws-iot-fleetwise/README.md
- recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge.bb
- Adds aws-iot-fleetwise-edge recipe
> Add aws-iot-fleetwise-edge recipe (gatesgarth)

- recipes-sdk/aws-iot-device-sdk-python-v1/aws-iot-device-sdk-python-v1_1.5.2.bb
- recipes-sdk/aws-iot-device-sdk-python-v1/aws-iot-device-sdk-python-v1_git.bb
- recipes-sdk/aws-iot-device-sdk-python-v1/files/0001-Replace-distutils-with-setuptools.patch
no recipe should use a floating version
> Hardknott aws iot device sdk python v1 fix autorev

- recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.17.32.bb
> aws-crt-cpp: upgrade 0.17.29 -> 0.17.32

- .github/CODEOWNERS
Update the codeowners file for the new org.
> github: update codeowners file.

- recipes-sdk/aws-crt-python/aws-crt-python_0.13.14.bb
- recipes-sdk/aws-crt-python/files/0002-disable-building-of-depending-libs.patch
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.11.3.bb
This should fix: https://github.com/aws4embeddedlinux/meta-aws/issues/426
> Master fix aws crt python v2

- CONTRIBUTING.md
- README.md
README.md:
remove firecracker info
add kirkstone release info (test not yet working)
CONTRIBUTING.md
add contributing CI info
> README.md, CONTRIBUTING.md

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.16.9.1.bb
> corretto-11-bin: enable auto upgrade and upgrade

- recipes-sdk/s2n/s2n/run-ptest
- recipes-sdk/s2n/s2n_1.3.30.bb
ptest: idea is to check if aws-c-iot is linked against s2n
> s2n: add ptest, changes acc. to oelint-adv

- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.30.bb
- recipes-sdk/aws-sdk-cpp/files/run-ptest
ptest: run integration tests
oelint-adv: no errors, no warnings
all libs: now all libs a build by default, separate packages, aws-sdk-cpp package contains all libs
> aws-sdk-cpp: ptest, oelint-adv, all libs

- recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
from
06c235948a673b240be32fe5f8241feb675d6cc8
to
b8ecca63791e6a4f9559b47d32132144d2d191ab
> amazon-s3-gst-plugin: version upgrade

- recipes-devtools/amazon-corretto/corretto-17-bin/run-ptest
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.6.10.1.bb
version upgrade:
17.0.5.8.1 -> 17.0.6.10.1
> corretto-17-bin: add ptest, fix oelint-adv warn + err, version upgrade

- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.29.bb
https://github.com/aws/aws-sdk-cpp/issues/2242
> aws-sdk-cpp: fix more, but not all libs building with for arm32

- recipes-sdk/aws-crt-python/files/run-ptest
fix cpython unittest error: https://github.com/python/cpython/issues/90579
> aws-crt-python: fix ptests for dunfell

- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2/run-ptest
fix cpython unittest error: python/cpython#90579
> aws-iot-device-sdk-python-v2: fix ptest for dunfell

- recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.4.bb
fix issue [3145](https://github.com/aws4embeddedlinux/meta-aws/issues/3145)
> greengrass-bin: replace WORKDIR with S

- recipes-devtools/python/python3-boto3_1.26.103.bb
- recipes-devtools/python/python3-botocore_1.29.103.bb
python3-boto3: 1.26.98 -> 1.26.103
python3-botocore: 1.29.98 -> 1.29.103
> python3-boto3, python3-botocore: upgrade

- recipes-support/aws-cli/aws-cli_1.27.120.bb
move this https://github.com/aws4embeddedlinux/meta-aws/pull/3514 upstream, see CONTRIBUTIONS.
> aws-cli: install examples in dedicated package to optimize storage use

- recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic/ptest_result.py
- recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic/run-ptest
- recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
got those errors:
ptests which had no test results:
['amazon-kvs-producer-pic']
> amazon-kvs-producer-pic: change ptest mechanism

- recipes-iot/aws-iot-greengrass/README.md
- recipes-iot/aws-iot-greengrass/files/config.yaml.template
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
Adding another env variable to allow changing of FLEET_PROVISIONING_TEMPLATE_NAME.
> Add FLEET_PROVISIONING_TEMPLATE_NAME

- .github/workflows/auto-update.yml
> auto-update.yml: change to ubuntu-22.04

- .github/workflows/auto-update.yml
libegl1-mesa libsdl1.2-dev mesa-common-dev
> auto-update.yml: remove not necessary packages

- recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
- recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
https://bugzilla.yoctoproject.org/show_bug.cgi?id=15227
> firecracker-bin, jailer-bin: add INHIBIT_PACKAGE_STRIP

- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.bb
fixed: https://github.com/awslabs/aws-iot-device-client/issues/411
> aws-iot-device-client: readd, upgrade 1.8. -> 1.9.

- conf/machine/aws-ec2-arm64.conf
fix https://github.com/aws4embeddedlinux/meta-aws/issues/6534
> aws-ec2-arm64: Improve arm64 tuning

- recipes-cloud/amazon-cloudwatch-publisher/amazon-cloudwatch-publisher_1.2.4.bb
- recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
- recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
- recipes-devtools/amazon-corretto/corretto-bin-common.inc
- recipes-sdk/aws-c-io/aws-c-io_0.13.36.bb
search here: https://nvd.nist.gov/products/cpe/search
> add CVE_PRODUCT information for the recipes that are available

- recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
- recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13_2.patch
-> https://github.com/aws-samples/aws-iot-securetunneling-localproxy/pull/136
> aws-iot-securetunneling-localproxy: fix GCC 13 build

- recipes-devtools/python/python3-jmespath_%.bbappend
- recipes-devtools/python/python3-ruamel-yaml-clib_0.2.7.bb
- recipes-devtools/python/python3-urllib3-1.x_1.26.18.bb
- recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.13.bb
- recipes-sdk/aws-crt-python/aws-crt-python_0.20.2.bb
- recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
- recipes-support/aws-cli-v2/aws-cli-v2/run-ptest
- recipes-support/aws-cli-v2/aws-cli-v2_2.15.9.bb
this is not just a simple upgrade of aws-cli, this require new package system pep517 etc.
> add new recipe aws-cli-v2

- scripts/ec2-ami/README.md
> ec2-ami: clarify the login user.

- recipes-devtools/amazon-corretto/corretto-8-bin_8.402.08.1.bb
> corretto-8-bin: upgrade 8.392.08.1 -> 8.402.08.1

- conf/layer.conf
> layer.conf: change compatibility to scarthgap

- recipes-devtools/amazon-corretto/corretto-21-bin_21.0.2.14.1.bb
> corretto-21-bin: upgrade 21.0.2.13.1 -> 21.0.2.14.1

- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.10.8.1.bb
> corretto-17-bin: upgrade 17.0.10.7.1 -> 17.0.10.8.1

- recipes-sdk/s2n/s2n/run-ptest
https://github.com/aws/s2n-tls/issues/4442
> s2n: disable shutdown test

- recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
- recipes-support/aws-cli-v2/aws-cli-v2_2.15.26.bb
> aws-cli-v2: upgrade 2.15.24 -> 2.15.26

- recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
- recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
> aws-iot-securetunneling-localproxy: boost 1.84 format include missing

- recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_1.1.0.bb
- recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-c_1.5.2.bb
- recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.10.0.bb
depending recipes:
amazon-kvs-producer-sdk-c: upgrade 1.5.0 -> 1.5.2
amazon-kvs-producer-pic: upgrade git -> 1.1.0
> amazon-kvs-webrtc-sdk: upgrade 1.9.1 -> 1.10.0

- recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
- recipes-multimedia/amazon-s3-gst-plugin/files/vaLog.patch
https://github.com/amzn/amazon-s3-gst-plugin/issues/44
> amazon-s3-gst-plugin: fix for aws-sdk-cpp log interface change

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.22.7.1.bb
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.10.8.1.bb
- recipes-devtools/amazon-corretto/corretto-21-bin_21.0.2.14.1.bb
- recipes-devtools/amazon-corretto/corretto-8-bin_8.402.08.1.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
Closes #7995
Added RPROVIDES for java virtual machine recipes, switched greengrass RDEPENDS to meta package.
> Define RPROVIDES for corretto recipes.

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.23.9.1.bb
- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.11.9.1.bb
- recipes-devtools/amazon-corretto/corretto-21-bin_21.0.3.9.1.bb
- recipes-devtools/amazon-corretto/corretto-8-bin_8.412.08.1.bb
corretto-8:·8.402.08.1·->·8.412.08.1
corretto-11: 11.0.22.7.1 -> 11.0.23.9.1
corretto-17: 17.0.10.8.1 -> 17.0.11.9.1
corretto-21: 21.0.2.14.1 -> 21.0.3.9.1
> corretto*: upgrade

- .github/workflows/auto-backport.yml
- .github/workflows/auto-recipe-update.yml
- .github/workflows/backport-based-on-label
> .github: scarthgap release changes, naming

- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.320.bb
> aws-sdk-cpp: upgrade 1.11.319 -> 1.11.320

- recipes-devtools/python/python3-boto3_1.34.100.bb
- recipes-devtools/python/python3-botocore_1.34.100.bb
- recipes-support/aws-cli/aws-cli_1.32.100.bb
> 2024 05 08 kirkstone next manual backports

- recipes-devtools/python/python3-boto3_1.34.100.bb
- recipes-devtools/python/python3-botocore_1.34.100.bb
- recipes-support/aws-cli/aws-cli_1.32.100.bb
> 2024 05 08 scarthgap next manual backports

- recipes-iot/aws-iot-greengrass/greengrass-bin-demo.bb
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.5.bb
Make it dependent on UNPACKDIR instead
> greengrass-bin, greengrass-bin-demo: Switch away from S = WORKDIR

- recipes-sdk/aws-crt-python/aws-crt-python_0.20.9.bb
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.21.4.bb
https://github.com/aws/aws-iot-device-sdk-python-v2/blob/83c323bc1cdf7b84fc9405c8c9fa39e2b297408e/documents/FAQ.md?plain=1#L49
https://github.com/aws4embeddedlinux/meta-aws/issues/8536
> aws-crt-python, aws-iot-device-sdk-python-v2: add proper versioning

- recipes-sdk/aws-c-common/aws-c-common_0.9.19.bb
> aws-c-common: fix ptest WORKDIR -> UNPACKDIR

- recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/amazon-kvs-producer-sdk-cpp-deps.patch
> amazon-kvs-producer-sdk-cpp: Fix patch status string

- recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.1.1.bb
- recipes-iot/aws-iot-fleetwise/files/boost_filesystem_extension.patch
> aws-iot-fleetwise-edge: Fix boost filesystem extension deprication

- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.2.bb
> aws-iot-device-client: fix ptest UNPACKDIR

- recipes-sdk/s2n/s2n/run-ptest
> s2n: disable failing ptests

- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning/run-ptest
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.7.bb
> add aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning

- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning/run-ptest
> aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning: fix ptest

- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub.bb
> aws-iot-device-sdk-cpp-v2-samples*: suppress QA error

- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.2.bb
- recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.10.2.bb
- recipes-sdk/aws-c-auth/aws-c-auth_0.7.22.bb
- recipes-sdk/aws-c-cal/aws-c-cal_0.7.1.bb
- recipes-sdk/aws-c-common/aws-c-common_0.9.23.bb
- recipes-sdk/aws-c-compression/aws-c-compression_0.2.18.bb
- recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.2.bb
- recipes-sdk/aws-c-http/aws-c-http_0.8.3.bb
- recipes-sdk/aws-c-io/aws-c-io_0.14.11.bb
- recipes-sdk/aws-c-iot/aws-c-iot_0.1.21.bb
- recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.4.bb
- recipes-sdk/aws-c-s3/aws-c-s3_0.6.1.bb
- recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.16.bb
- recipes-sdk/aws-checksums/aws-checksums_0.1.18.bb
- recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.551.0.bb
> suppress QA errors *-ptest: buildpaths

- recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.10.2.bb
- recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.551.0.bb
> amazon-kvs-webrtc-sdk, amazon-ssm-agent: suppress QA errors

- recipes-sdk/aws-lc/aws-lc_1.32.0.bb
> aws-lc: add alternative name to avoid conflict with openssl-bin

- recipes-sdk/aws-lc/aws-lc_1.32.0.bb
> aws-lc: fix alternate name mechanism

- recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/global-thread-sleep-linkerror.patch
- recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.4.1.bb
fix https://github.com/aws4embeddedlinux/meta-aws/issues/1701
> amazon-kvs-producer-sdk-cpp: fix globalThreadSleep link error

- recipes-devtools/amazon-corretto/corretto-11-bin_11.0.24.8.1.bb
> corretto-11-bin: fix arm version

- README.md
> README.md: update copyright year

- recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
- recipes-support/aws-cli-v2/aws-cli-v2_2.17.56.bb
> aws-cli-v2: upgrade 2.15.26 -> 2.17.56

- .github/workflows/backport-based-on-label.yml
> backport-based-on-label.yml: add styhead

- .github/workflows/auto-approve-and-enable-auto-merge.yml
- .github/workflows/ff-merge.yml
- .github/workflows/pr-cve-check.yml
> gh actions: set fixed versions, use of gh auto merge

- recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.11.0.bb
> amazon-kvs-webrtc-sdk: upgrade 1.10.2 -> 1.11.0

- .github/workflows/auto-approve-and-enable-auto-merge.yml
> auto-approve-and-enable-auto-merge.yml: fix PR number

- recipes-devtools/python/python3-boto3_1.35.35.bb
- recipes-devtools/python/python3-botocore_1.35.35.bb
- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.421.bb
- recipes-support/aws-cli/aws-cli_1.35.1.bb
> 2024 10 08 styhead next backport

- recipes-devtools/python/python3-boto3_1.35.35.bb
- recipes-devtools/python/python3-botocore_1.35.35.bb
- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.421.bb
- recipes-support/aws-cli/aws-cli_1.35.1.bb
> 2024 10 08 scarthgap next backport

- recipes-devtools/python/python3-boto3_1.35.35.bb
- recipes-devtools/python/python3-botocore_1.35.35.bb
- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.421.bb
- recipes-support/aws-cli/aws-cli_1.35.1.bb
> 2024 10 08 kirkstone next backport

- .github/workflows/auto-approve-and-enable-auto-merge.yml
As gh tool did not work as advertised.
> auto-approve-and-enable-auto-merge.yml: switch back to automerge action

- .github/workflows/auto-approve-and-enable-auto-merge.yml
- .github/workflows/auto-backport.yml
- .github/workflows/auto-recipe-update.yml
- .github/workflows/ff-merge.yml
- .github/workflows/nightly-cve-check.yml
- .github/workflows/oelint-adv.yml
- .github/workflows/pr-cve-check.yml
- .github/workflows/yocto-check-layer.yml
(cherry picked from commit 4977e14caf2eeecb942e58b6ac086606a84c1097)
> backport github workflows

- recipes-sdk/s2n/s2n_1.5.4.bb
> s2n: upgrade 1.5.3 -> 1.5.4

- recipes-sdk/aws-c-io/aws-c-io_0.14.19.bb
- recipes-sdk/s2n/s2n_1.5.5.bb
> 2024 10 14 scarthgap next aws c io

- recipes-sdk/aws-c-io/aws-c-io_0.14.19.bb
- recipes-sdk/s2n/s2n_1.5.5.bb
> 2024 10 14 kirkstone next aws c io

- .github/workflows/ff-merge.yml
> ff-merge.yml: update checkout version

- .github/workflows/build-test-recipe.yml
> build-test-recipe.yml: backport from master

- .github/workflows/build-test-recipe.yml
https://github.com/awslabs/amazon-kinesis-video-streams-pic/issues/259
> build-test-recipe.yml: disable amazon-kvs-producer-pic ptest for arm32

- .github/workflows/auto-recipe-update.yml
This is to not have overlapping PRs as the test mechanism will otherwise check all differences to the main and this will cause conflicts.
> auto-recipe-update: change delay from 300 to 1800s

- .github/workflows/build-test-recipe.yml
> build-test-recipe.yml: adding origin

- recipes-containers/firecracker-bin/firecracker-bin_1.10.1.bb
- recipes-containers/firecracker-bin/jailer-bin_1.10.1.bb
> firecracker, jailer -bin: upgrade 1.3.3. -> 1.10.1

- recipes-devtools/python/python3-ruamel-yaml-clib-native_0.2.12.bb
> python3-ruamel-yaml-clib-native: accept lic minor change

- recipes-devtools/python/python3-ruamel-yaml-clib-native_0.2.12.bb
> python3-ruamel-yaml-clib-native: added

- .github/workflows/build-test-recipe.yml
> build-test-recipe.yml: add DISTRO_FEATURES systemd

- recipes-iot/aws-iot-greengrass/greengrass-lite_git.bb
> greengrass-lite_git.bb: change WORKDIR to UNPACKDIR

- recipes-iot/aws-iot-greengrass/greengrass-lite_git.bb
> greengrass-lite_git.bb: add UPSTREAM_CHECK_COMMITS

- .github/workflows/build-test-recipe.yml
> build-test-recipe.yml: support building from other than master

- .github/workflows/build-test-all-branches.yml
This should build, test all branches on request or nightly.
> build-test-all-branches.yml: add

- recipes-iot/aws-iot-greengrass/greengrass-lite/greengrass-lite.yaml
> greengrass-lite.yaml: add platformOverride

- recipes-iot/aws-iot-greengrass/greengrass-lite_git.bb
> greengrass-lite_git.bb: upgrade git version

- recipes-iot/aws-iot-greengrass/greengrass-lite_2.0.0.bb
> greengrass-lite_2.0.0.bb: GreenGrass nucleus lite v2.0.0 release

- recipes-iot/aws-iot-greengrass/greengrass-lite_2.0.0.bb
> greengrass-lite_2.0.0.bb: Set release commit.

- recipes-iot/aws-iot-greengrass/greengrass-lite_2.0.0.bb
> greengrass-lite_2.0.0: fix release commit sha

- .github/workflows/build-test-recipe.yml
> build-test-recipe.yml: fix for pr from forks, push

- recipes-iot/aws-iot-greengrass/files/greengrass.service.diff
- recipes-iot/aws-iot-greengrass/greengrass-bin_2.14.0.bb
> greengrass-bin: upgrade 2.13.0 -> 2.14.0

- .github/workflows/build-test-all-branches.yml
- .github/workflows/build-test-recipe.yml
- .github/workflows/ff-merge.yml
- .github/workflows/pr-cve-check.yml
> github workflows: backport from master-next

- .github/workflows/pr-cve-check.yml
As greengrass-lite requires this and all build tests are changed to this distro.
> pr-cve-check.yml: change distro to poky-altcfg

- recipes-iot/aws-iot-greengrass/greengrass-lite/run-ptest
- recipes-iot/aws-iot-greengrass/greengrass-lite_2.0.0.bb
> greengrass-lite: fix ptest for greengrass-bin, 2nd try

- recipes-iot/aws-iot-greengrass/files/run-ptest
- recipes-iot/aws-iot-greengrass/greengrass-lite/run-ptest
- recipes-iot/aws-iot-greengrass/greengrass-lite_2.0.0.bb
Stopping of autostarted greengrass-bin from systemd.
> greengrass-bin: fix ptest, 3rd try

- recipes-iot/aws-iot-greengrass/greengrass-bin_2.14.0.bb
Disable startup of Greengrass, as we want to monitor this.
> greengrass-bin_2.14.0.bb: fix ptest

- .github/workflows/yocto-check-layer.yml
> yocto-check-layer.yml: fix to run with ubuntu 24.04.

- .github/workflows/build-test-recipe.yml
This will also make the step fail if error occurred.
> build-test-recipe.yml: rewrite error grep logic

- recipes-sdk/amazon-kvs-webrtc-sdk/files/run-ptest
> amazon-kvs-webrtc-sdk: add libasan preload

- recipes-iot/aws-iot-greengrass/greengrass-lite_2.0.1.bb
> greengrass-lite: version upgrade 2.0.0 -> 2.0.1

- .github/workflows/yocto-check-layer.yml
> yocto-check-layer.yml: bump gh action artifact version

- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.499.bb
> aws-sdk-cpp: upgrade 1.11.493 -> 1.11.499

- .github/workflows/build-test-recipe.yml
> build-test-recipe.yml: set 3GB for qemu

- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.35.0.bb
Need to look into findings when there is more time. Marked as TODO
> aws-iot-device-sdk-cpp-v2: disable sanitize tests

- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples.inc
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/openssl_suppressions.txt
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/run-ptest
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.35.0.bb
Need more time to check if this is a false positive
> aws-iot-device-sdk-cpp-v2: disable sanitizers

- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/openssl_suppressions.txt
> aws-iot-device-sdk-cpp-v2: suppress zalloc mem leak

- recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.9.1.bb
- recipes-sdk/amazon-kvs-webrtc-sdk/files/run-ptest
- recipes-sdk/amazon-kvs-webrtc-sdk/files/sanitizer_suppressions.txt
> amazon-kvs-webrtc-sdk: add sanitizer suppressions

- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.509.bb
(cherry picked from commit 64b1e2204e855bbded12e3cb60acd669e9515e9d)
> aws-sdk-cpp: upgrade 1.11.498 -> 1.11.509

- recipes-sdk/aws-iot-device-sdk-embedded-c/aws-iot-device-sdk-embedded-c_202412.00.bb
- recipes-sdk/aws-iot-device-sdk-embedded-c/files/run-ptest
SDK for connecting to AWS IoT from a device using embedded C
> aws-iot-device-sdk-embedded-c: add initial version

- recipes-cloud/amazon-cloudwatch-agent/amazon-cloudwatch-agent_1.300054.0.bb
- recipes-cloud/amazon-cloudwatch-agent/files/001-makefile.patch
- recipes-cloud/amazon-cloudwatch-agent/files/run-ptest
> amazon-cloudwatch-agent: add recipe

- README.md
> README.md: add actual date

- recipes-iot/aws-iot-greengrass/greengrass-lite/001-disable_strip.patch
- recipes-iot/aws-iot-greengrass/greengrass-lite/002-disable-cmake-req.patch
- recipes-iot/aws-iot-greengrass/greengrass-lite/greengrass-lite.yaml
- recipes-iot/aws-iot-greengrass/greengrass-lite/run-ptest
- recipes-iot/aws-iot-greengrass/greengrass-lite_git.bb
> greengrass-lite: add and a patch to compile with cmake 3.22

- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.35.1.bb
> aws-iot-device-sdk-cpp-v2: enable option to use system openssl

- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.10.0.bb
> aws-iot-device-client: update 1.9.13 -> 1.10.0

- .github/workflows/build-test-recipe.yml
As this conflicts with aws-iot-device-sdk-cpp-v2
> build-test-recipe.yml: disable aws-c-iot

- .github/workflows/build-test-recipe.yml
> build-test-recipe.yml: adding blank to separate excludes

- recipes-iot/aws-iot-greengrass/greengrass-bin_2.14.1.bb
This is to make the PACKAGECONFIG QA check happy.
> greengrass-bin: add dummy for fleetprovisioning

- .github/workflows/build-test-recipe.yml
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples.inc
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/001-shared-static-crt-libs.patch
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.35.1.bb
> aws-iot-device-sdk-cpp-v2: disable sanitizer checks

- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/openssl_suppressions.txt
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/run-ptest
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.35.1.bb
> aws-iot-device-sdk-cpp-v2: disable obsolete sanitizer loading

- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.551.bb
> aws-sdk-cpp: change WORKDIR to UNPACKDIR

- recipes-cloud/amazon-cloudwatch-publisher/amazon-cloudwatch-publisher_1.2.4.bb
- recipes-devtools/amazon-corretto/corretto-bin-common.inc
- recipes-devtools/python/python3-boto3_1.37.38.bb
- recipes-devtools/python/python3-botocore_1.37.38.bb
- recipes-devtools/python/python3-s3transfer_0.11.5.bb
- recipes-iot/aws-iot-device-client/aws-iot-device-client_1.10.0.bb
- recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.3.0.bb
- recipes-iot/aws-iot-greengrass/greengrass-lite_2.0.2.bb
- recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
- recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_1.1.0.bb
- recipes-sdk/aws-c-auth/aws-c-auth_0.9.0.bb
- recipes-sdk/aws-c-cal/aws-c-cal_0.9.0.bb
- recipes-sdk/aws-c-common/aws-c-common_0.12.2.bb
- recipes-sdk/aws-c-compression/aws-c-compression_0.3.1.bb
- recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.5.4.bb
- recipes-sdk/aws-c-http/aws-c-http_0.9.7.bb
- recipes-sdk/aws-c-io/aws-c-io_0.18.1.bb
- recipes-sdk/aws-c-iot/aws-c-iot_0.2.1.bb
- recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.12.3.bb
- recipes-sdk/aws-c-s3/aws-c-s3_0.7.15.bb
- recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.2.3.bb
- recipes-sdk/aws-checksums/aws-checksums_0.2.7.bb
- recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.32.4.bb
- recipes-sdk/aws-crt-python/aws-crt-python_0.26.1.bb
- recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.35.1.bb
- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.22.2.bb
- recipes-sdk/s2n/s2n_1.5.17.bb
- recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.2299.0.bb
- recipes-support/aws-cli/aws-cli_1.38.38.bb
As https://docs.yoctoproject.org/next/migration-guides/migration-5.1.html#s-workdir-no-longer-supported
> WORKDIR to UNPACKDIR

- recipes-support/aws-cli-v2/aws-cli-v2_2.27.0.bb
> aws-cli-v2: change from WORKDIR to UNPACKDIR

- recipes-sdk/aws-lc/aws-lc_1.49.1.bb
> aws-lc: WORKDIR to UNPACKDIR

- recipes-iot/aws-iot-greengrass/greengrass-lite/run-ptest
- recipes-iot/aws-iot-greengrass/greengrass-lite_2.1.0.bb
Also added FETCHCONTENT_SOURCE to comply with QA
"do_configure has network enabled"
> greengrass-lite: 2.0.2 -> 2.1.0

- .github/workflows/auto-backport.yml
- .github/workflows/build-test-all-branches.yml
- .github/workflows/ff-merge.yml
> change styhead to walnascar as the actual supported release

- recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_1.1.0.bb
- recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.12.1.bb
> amazon-kvs-producer-pic, amazon-kvs-webrtc-sdk: fix ptest dir

- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.573.bb
> aws-sdk-cpp: add INSANE_SKIP buildpaths for dev package

- recipes-sdk/aws-c-iot/aws-c-iot_0.2.1.bb
> aws-c-iot: remove not necessary dependency aws-crt-cpp

- recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.12.1.bb
To allow the non gstreamer examples to work.
> amazon-kvs-webrtc-sdk: add sample files

- recipes-sdk/aws-crt-cpp/aws-crt-cpp/run-ptest
> 2025 05 27 master next fix aws crt cpp

- conf/layer.conf
> layer.conf: LAYERSERIES_COMPAT set to whinlatter

- .github/workflows/build-test-recipe.yml
as this is conflicting with the separate packages
> build-test-recipe.yml: exclude aws-iot-device-sdk-embedded-c

- .github/workflows/build-test-recipe.yml
- recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.12.1.bb
- recipes-sdk/aws-c-common/aws-c-common_0.12.4.bb
- recipes-sdk/aws-c-common/files/run-ptest
- recipes-sdk/aws-crt-cpp/aws-crt-cpp/run-ptest
- recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.32.5.bb
> amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk: disable warning for arm32

- .github/workflows/build-test-recipe.yml
> build-test-recipe.yml: disable build of aws-iot-device-sdk-embedded-c

- recipes-devtools/python/python3-boto3_1.39.13.bb
- recipes-devtools/python/python3-botocore_1.39.13.bb
- recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.612.bb
> 2025 07 28 scarthgap next backport

- recipes-devtools/amazon-corretto/corretto-17-bin_17.0.16.8.1.bb
- recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.3.2.bb
> 2025 07 28 kirkstone next backport3

- recipes-containers/firecracker-bin/firecracker-bin_1.10.1.bb
- recipes-containers/firecracker-bin/jailer-bin_1.10.1.bb
> firecracker-bin: upgrade 1.3.3 -> 1.10.1

- recipes-sdk/aws-c-auth/aws-c-auth_0.9.0.bb
- recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.5.5.bb
> 2025 07 28 kirkstone next backport5

- recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.24.0.bb
> aws-iot-device-sdk-python-v2: 1.22.2 -> 1.24.0

- recipes-sdk/aws-lc/aws-lc_1.56.0.bb
> 2025 07 28 kirkstone next backport6

- recipes-sdk/aws-crt-python/aws-crt-python_0.27.4.bb
- recipes-support/aws-cli-v2/aws-cli-v2_2.27.63.bb
> 2025 07 31 scarthgap next backport2

- recipes-sdk/aws-crt-python/aws-crt-python_0.27.4.bb
That also needs explicit set of OpenSSL paths.
Closes: #13233
> aws-crt-python: fix nativesdk build

- .github/workflows/build-test-recipe.yml
> build-test-recipe.yml: exclude deleted files from diff, build test

- recipes-sdk/aws-c-cal/aws-c-cal_0.9.3.bb
> aws-c-cal: fix ptest, add missing patch

- recipes-iot/aws-iot-greengrass/greengrass-component-helloworld-sdk-lite/run-ptest
- recipes-iot/aws-iot-greengrass/greengrass-component-helloworld-sdk-lite_1.0.0.bb
> greengrass-component-helloworld-sdk-lite: fix ptest

- .github/workflows/build-test-recipe.yml
> build-test-recipe.yml: add support for merge queue builds

- .github/workflows/build-test-recipe.yml
> build-test-recipe.yml: add support for merge queue builds fix2
